pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: "main", url: 'https://github.com/Erenen1/jenkins-nodejs-example.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh 'npm test'
                }
            }
        }
    }
    post {
        success {
            echo 'Build ve Test Başarılı!'
        }
        failure {
            echo 'Build veya Test Başarısız!'
        }
    }
}
