pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                //git branch: "main", url: 'https://github.com/Erenen1/jenkins-nodejs-example.git'
                checkout([$class: 'GitSCM', branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Erenen1/jenkins-nodejs-example.git',
                        credentialsId: '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'
                    ]]
                ])
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh 'npm test'
                }
            }
        }
    }
    post {
        success {
            echo 'Build ve Test Başarılı!'
        }
        failure {
            echo 'Build veya Test Başarısız!'
        }
    }
}
