pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                //git branch: "main", url: 'https://github.com/Erenen1/jenkins-nodejs-example.git' repo public ise 
                git credentialsId: 'd3267b64-befd-457d-b864-9df9a82a20d7', url: 'https://github.com/Erenen1/jenkins-nodejs-example.git'

            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh 'npm test'
                }
            }
        }
    }
    post {
        success {
            echo 'Build ve Test Başarılı!'
        }
        failure {
            echo 'Build veya Test Başarısız!'
        }
    }
}
